#!/bin/bash

for N in {2..10} ; do for X in {0..2} ; do for Z in {0..2} ; do for b in $(seq 1.0 1.0 5.0) ; do julia main.jl mixedstate $N --zfield $Z --xfield $X --beta $b -M 10000 -s 10 ; done ; done ; done ; done
