#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --mem=4G
#SBATCH --mail-user=emerali@uwaterloo.ca
#SBATCH --mail-type=FAIL
#SBATCH --account=rrg-rgmelko-ab
#SBATCH --output=/scratch/ejaazm/qmc_sims/transition_matrices/logs/mcmc-output-%x-%A-%a.out

echo delta=$delta
echo p=$p
echo eps=$eps


module load StdEnv/2020 julia/1.5.2

julia --compiled-modules=no --project=../ rydberg_experiment_saveall.jl \
   groundstate 51 \
   --omega 1.0 -R 1.2 --delta $delta \
   -n 1000000 -b 10 --mb-prob $p --epsilon $eps \
   --seed 1234 -M 12000 --runstats 500

# for p in $(seq 0.0 0.5 1.0)
# do
#     julia --compiled-modules=no --project=../ rydberg_cleanup.jl $nY $delta $M $p
# done

# julia --compiled-modules=no --project=../ rydberg_cleanup.jl --histograms $nY $delta $M 0.0
